### ISSUE TITLE
Search is not working properly

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-store#34]
Searching with "digit-text" (e.g., 100-gene) returns a 500 error (seen in from the inspect)
If you paste such term directly the search result is not correct, the list of articles stays the same.

Selecting a facet after such search keeps returning 500

**Comment by fabubaker** [comment]
So, in the search bar you can search for file ids as well as fulltext searches.
We check if the search input is an int and if it is, we perform a file id search. Otherwise, we do a text search.

The problem here is that in ruby, we have this:

```
irb(main):001:0> '70-gene'.to_i
=> 70
``` 
'70-gene' is recognized as file-id `70`.
You can see where this is going...

**Comment by mouradvt04** [comment]
Searching “1420” returns no results but “1420*”, “1420+”, etc. yields results where “1420” is found not really a big deal but, also search “placebo-“ or “placebo” yield the same results
Is this what we want?

**Comment by hammady** [comment]
Searching with a pure number is intended for lookup by article id.
For the second case, this is a full-text search where stemming and stop-word removal happens. This is the same behavior for Solr.
